// Generated by CoffeeScript 1.6.3
(function() {
  var socket;

  socket = io.connect("http://localhost:1025");

  socket.on("news", function(data) {
    console.log("this is test:");
    console.log(data);
    socket.emit("my other event", {
      my: "data"
    });
  });

}).call(this);
