// Generated by CoffeeScript 1.6.3
(function() {
  var app, fs, handler, i, io;

  i = 0;

  app = require("http").createServer(handler);

  io = require("socket.io").listen(app);

  fs = require("fs");

  app.listen(1025);

  handler = function(req, res) {
    fs.readFile(__dirname + "/index.html", function(err, data) {
      if (err) {
        res.writeHead(500);
        return res.end("Error loading index.html");
      }
      res.writeHead(200);
      res.end(data);
    });
  };

  io.sockets.on("connection", function(socket) {
    var myloop;
    myloop = function() {
      console.log("connection established");
      socket.emit("news", {
        hello: "world:andre" + i
      });
      i = i + 1;
      return setTimeout(function() {
        return myloop();
      }, 1000);
    };
    myloop();
    socket.on("my other event", function(data) {
      console.log(data);
    });
  });

}).call(this);
