// Generated by CoffeeScript 1.6.3
(function() {
  var io;

  io = require("socket.io").listen(1025);

  io.sockets.on("connection", function(socket) {
    socket.emit("news", {
      hello: "world"
    });
    socket.on("my other event", function(data) {
      console.log(data);
    });
  });

}).call(this);
