// Generated by CoffeeScript 1.6.3
(function() {
  var conns, server, ws;

  conns = new Array();

  ws = require("websocket-server");

  server = ws.createServer();

  server.addListener("connection", function(conn) {
    console.log("connection...");
    conns.push(conn);
    conn.addListener("message", function(msg) {
      var i;
      console.log(msg);
      i = 0;
      while (i < conns.length) {
        if (conns[i] !== conn) {
          conns[i].send(msg);
        }
        i++;
      }
    });
  });

  server.listen(1025);

  console.log("running......");

}).call(this);
