// Generated by CoffeeScript 1.6.3
(function() {
  var doSend, init, onClose, onError, onMessage, onOpen, output, testWebSocket, websocket, writeToScreen, wsUri;

  wsUri = "ws://localhost:1025/";

  output = void 0;

  websocket = new WebSocket(wsUri);

  init = function() {
    output = document.getElementById("output");
    testWebSocket();
  };

  testWebSocket = function() {
    websocket.onopen = function(evt) {
      onOpen(evt);
    };
    websocket.onclose = function(evt) {
      onClose(evt);
    };
    websocket.onmessage = function(evt) {
      onMessage(evt);
    };
    websocket.onerror = function(evt) {
      onError(evt);
    };
  };

  onOpen = function(evt) {
    writeToScreen("CONNECTED");
    doSend("WebSocket rocks 中文" + Math.random(0, 1));
  };

  onClose = function(evt) {
    writeToScreen("DISCONNECTED");
  };

  onMessage = function(evt) {
    writeToScreen("<span style=\"color: blue;\">RESPONSE: " + evt.data + "</span>");
    websocket.close();
  };

  onError = function(evt) {
    writeToScreen("<span style=\"color: red;\">ERROR:</span> " + evt.data);
  };

  doSend = function(message) {
    writeToScreen("SENT: " + message);
    websocket.send(message);
  };

  writeToScreen = function(message) {
    var pre;
    pre = document.createElement("p");
    pre.style.wordWrap = "break-word";
    pre.innerHTML = message;
    output.appendChild(pre);
  };

  window.addEventListener("load", init, false);

}).call(this);
